dist: bionic
language: cpp

branches:
  only:
    - master

compiler:
  - clang-3.9
  - clang   # clang 7
  - clang-9
  - clang-10
  - gcc-4.8
  - gcc     # gcc 7.4
  - gcc-9
  - gcc-10

jobs:
  include:
    - compiler: clang-3.9
    - name: "Build with LLVM/Clang 3.9"
      addons:
        apt:
          packages:
          - clang-3.9
      env:
      - MATRIX_EVAL="CC=clang-3.9 CXX=clang++-3.9"

    - compiler: clang
    - name: "Build with LLVM/Clang 7"
      env:
      - MATRIX_EVAL="CC=clang CXX=clang++"

    - compiler: clang-9
    - name: "Build with LLVM/Clang 9"
      addons:
        apt:
          packages:
          - clang-9
      env:
      - MATRIX_EVAL="CC=clang-9 CXX=clang++-9"

    - compiler: clang-10
    - name: "Build with LLVM/Clang 10"
      addons:
        apt:
          sources:
          - sourceline: 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-10 main'
          key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
          packages:
          - clang-10
      env:
      - MATRIX_EVAL="CC=clang-10 CXX=clang++-10"

    - compiler: gcc-4.8
    - name: "Build with GCC 4.8"
      addons:
        apt:
          packages:
          - gcc-4.8
          - g++-4.8
      env:
      - MATRIX_EVAL="CC=gcc-4.8 CXX=g++-4.8"

    - compiler: gcc
    - name: "Build with GCC 7.4"
      env:
      - MATRIX_EVAL="CC=gcc CXX=g++"

    - compiler: gcc-9
    - name: "Build with GCC 9"
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          packages:
          - gcc-9
          - g++-9
      env:
      - MATRIX_EVAL="CC=gcc-9 CXX=g++-9"

    - compiler: gcc-10
    - name: "Build with GCC 10"
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          packages:
          - gcc-10
          - g++-10
      env:
      - MATRIX_EVAL="CC=gcc-10 CXX=g++-10"

before_script: 
- cmake --version
- eval "${MATRIX_EVAL}"
- $CC --version
- $CXX --version

script:
- mkdir ./build
- cd ./build
- cmake ..
- cmake --build .
- ctest
- cd ..
